export const appImages = {
    'plant_corner':require('../assets/plant_corner.png'),
    'profile_placeholder':require('../assets/profile_placeholder.png'),
    'plant1':require('../assets/plant1.png'),
    'plant2':require('../assets/plant2.png'),
    'plant3':require('../assets/plant3.png'),
    'alho':require('../assets/alho.png'),
    'pimenta_do_reino':require('../assets/pimenta_do_reino.png'),
    'mirtilo':require('../assets/mirtilo.png'),
    'suculenta':require('../assets/suculenta.png'),
    'morango':require('../assets/morango.png'),
    'tomate':require('../assets/tomate.png'),
    'coentro':require('../assets/coentro.png'),
    'hortela':require('../assets/hortela.png'),
    'alface':require('../assets/alface.png'),
    'cebola':require('../assets/cebola.png'),
}